name: publish

on:
  release:
    types: [published]

jobs:
  build:
    name: publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ubuntu-latest-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ubuntu-latest-gradle-

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Build with Gradle
        run: ./gradlew -Psemver='${{ github.event.release.tag_name }}' build
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Add Artifacts to Github Release
        uses: alexellis/upload-assets@0.4.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["./build/libs/*.jar"]'

      - name: Publish to Github Packages
        run: ./gradlew -Psemver='${{ github.event.release.tag_name }}' publish
        env:
          GITHUB_MAVEN_URL: 'https://maven.pkg.github.com/${{ github.repository }}'
          GITHUB_TOKEN: ${{ github.token }}
